[tox]
minversion = 3.28.0
envlist = py39-molecule-podman
skipsdist = true
isolated_build = true

[testenv:py39-molecule-podman]
deps =
    ansible-core>=2.14,<2.16
    molecule>=6.0
    molecule-plugins[podman]>=23.5
commands =
    ansible-galaxy collection install containers.podman --force -p /opt/vector-role/.ansible/collections
    molecule test -s molecule_podman_test --destroy=always
setenv =
    ANSIBLE_COLLECTIONS_PATH=/opt/vector-role/.ansible/collections:/root/.ansible/collections